tools:
    external_code_coverage: false

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
            environment:
                php:
                    version: 7.2
