language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-dist --no-interaction

script:
  - phpunit --coverage-text
