language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    # disable TLS for composer because openssl is disabled for PHP 5.3.3 on travis
    # see: https://blog.travis-ci.com/upcoming_ubuntu_11_10_migration/
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- disable-tls true; fi;
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- secure-http false; fi;
    - composer install --prefer-dist --no-interaction

script:
    - mkdir -p build/logs
    - phpunit -v --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
