language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

install:
    - composer self-update

before_script:
    # disable TLS for composer because openssl is disabled for PHP 5.3.3 on travis
    # see: https://blog.travis-ci.com/upcoming_ubuntu_11_10_migration/
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- disable-tls true; fi;
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- secure-http false; fi;
    - composer install --prefer-dist --no-interaction

script:
    - phpunit --coverage-clover=coverage.clover

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
