language: php

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: 7.2
          env: SYMFONY_PHPUNIT_VERSION=7.5
        - php: 7.3
          env: SYMFONY_PHPUNIT_VERSION=7.5 CS_FIXER=run
        - php: 7.4
          env: SYMFONY_PHPUNIT_VERSION=7.5
        - php: nightly
          env: SYMFONY_PHPUNIT_VERSION=7.5
    fast_finish: true
    allow_failures:
        - php: nightly

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
    - composer self-update

before_script:
    - if [ "$CS_FIXER" = "run" ]; then composer require phpstan/phpstan phpstan/phpstan-phpunit --dev -n ; fi;
    - composer install -o --prefer-dist --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/simple-phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;
    # only install phpstan when we need it
    - if [ "$CS_FIXER" = "run" ]; then composer require phpstan/phpstan --no-progress --no-suggest ; fi;
    - if [ "$CS_FIXER" = "run" ]; then composer require phpstan/phpstan-phpunit --no-progress --no-suggest ; fi;
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/phpstan analyse src tests --no-progress --level 1 ; fi;

after_script:
    - php vendor/bin/php-coveralls -v -x build/logs/clover.xml
